# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='员工编号')),
                ('user_password', models.CharField(max_length=40, verbose_name='密码')),
            ],
        ),
    ]
