# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=80, verbose_name='员工名字'),
            preserve_default=False,
        ),
    ]
