# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.BooleanField(default=True),
        ),
    ]
