# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='describe',
            field=models.CharField(blank=True, max_length=100, verbose_name='自我简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=100, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, verbose_name='手机号码'),
        ),
    ]
