# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170410_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id'], 'verbose_name': '作业', 'verbose_name_plural': '作业'},
        ),
        migrations.AddField(
            model_name='task',
            name='pulishId',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='blog.teacher'),
            preserve_default=False,
        ),
    ]
