# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170410_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pulishId',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='blog.Teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='pulishId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Teacher'),
        ),
    ]
