# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170410_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='pulishId',
            new_name='coursePubliser',
        ),
        migrations.AlterField(
            model_name='course',
            name='coursePubliser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Teacher'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pulishId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Teacher'),
        ),
    ]
