# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170410_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='pulishId',
            new_name='taskPub',
        ),
        migrations.RemoveField(
            model_name='course',
            name='coursePubliser',
        ),
        migrations.AddField(
            model_name='course',
            name='coursePub',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='blog.Teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='taskPub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Teacher'),
        ),
    ]
