# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170410_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoName', models.CharField(blank=True, max_length=20, null=True, verbose_name='视频名')),
                ('videoDesc', models.CharField(blank=True, max_length=20, null=True, verbose_name='视频简述')),
                ('videoSrc', models.CharField(blank=True, max_length=100, null=True, verbose_name='视频地址')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='courseDesc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='课程简述'),
        ),
        migrations.AlterField(
            model_name='course',
            name='coursePub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Teacher'),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskDesc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='作业内容'),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskPub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Teacher'),
        ),
        migrations.AddField(
            model_name='video',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Course'),
        ),
    ]
