# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20170411_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='答案')),
                ('studentDo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Student')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '答案',
                'verbose_name': '答案',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='coursePub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Teacher'),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskPub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Teacher'),
        ),
        migrations.AddField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Task'),
        ),
    ]
