# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170412_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='studentDo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='coursePub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Teacher'),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskPub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Teacher'),
        ),
    ]
